accounts/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import SignUpView
from . import views

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', views.profile, name='profile'),
    path('update/', views.update_profile, name='update_profile'),
]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name="cart_remove"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('test_app.urls', 'test_app'), namespace='test_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_app/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/', views.product_list, name='catalog'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
    views.product_detail,
    name='product_detail'),
    url(r'^(?P<category_slug>[-\w]+)/$',
    views.product_list,
    name='product_list_by_category'),
]

test_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    image = models.ImageField(upload_to='categories/', blank=True)
    parent = models.ForeignKey('self', blank=True, null=True, related_name="children", on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категория'
        unique_together = ('slug', 'parent',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('test_app:product_list_by_category',
                        args=[self.slug])

    def get_sub_categories(self):
        return Category.object.filter(parent=self)

class Product(models.Model):
    category = models.ForeignKey(Category, related_name="products", on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    #image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    stock = models.PositiveIntegerField()
    product_information = models.TextField(blank=True)
    description = models.TextField(blank=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('test_app:product_detail',
                    args=[self.id, self.slug])

    def get_title_image(self):
        if ProductImage.objects.filter(product=self).count() > 0:
            return ProductImage.objects.filter(product=self)[0]

    def get_images(self):
        return ProductImage.objects.filter(product=self)

class ProductImage(models.Model):
    product = models.ForeignKey(Product, default=None, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

test_app/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.db.models import Q
from .models import Product, Category
from cart.forms import CartAddProductForm

def index(request):
    products = Product.objects.all()
    return render(request, 'test_app/index.html', {'products':products})

def product(request):
    return render(request, 'test_app/productdetail.html', {})

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
        id=id,
        slug=slug,
        available=True,)
    cart_product_form = CartAddProductForm()
    return render(request, 'test_app/productdetail.html', {'product': product, 'cart_product_form': cart_product_form})

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(Q(category=category) | Q(category__parent=category))
    else:
        products = products[:12]
    return render(request, 'test_app/catalog.html', {'category':category,
                                                    # 'categories':categories,
                                                    'products':products,
                                                    })

test_app/templates/test_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block meta %}

  {% endblock meta %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
  <link rel="stylesheet" href={% static 'test_app/style.css' %}>
  <link rel="stylesheet" href={% static 'test_app/slider.css' %}>
  <link rel="stylesheet" href={% static 'test_app/burger.css' %}>
  <link rel="stylesheet" href={% static 'test_app/profile.css' %}>
  <link rel="stylesheet" href={% static 'test_app/cart.css' %}>
  <link rel="stylesheet" href={% static 'test_app/form.css' %}>
  <script src="https://use.fontawesome.com/40003d2102.js"></script>
  <title>Document</title>
</head>
<body>
  <div class="container">
  <div class="rov">
    <div class="dropdown">
  <button class="btn btn-primary">☰</button>
  <div class="dropdown-content">
    {% for category in categories %}
    <a rel="nofollow" rel="noreferrer" href="{{category.get_absolute_url}}">{{category.name}}</a>
    {% endfor %}
  </div>
</div>

    <div class="logoHeader">
      <a href="{% url 'test_app:index' %}"><img src="{% static 'images/logo.png' %}" alt=""></a>
    </div>


    <a class="btn btn-primary" href="{% url 'test_app:catalog' %}">Каталог</a>
    <input type="text" name="searchText" value="" class="searchInput" placeholder="Я ищу...">
    <div class="cartHeader">
       {% with total_items=cart|length %}<a class="cart" href="{% url 'cart:cart_detail' %}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
</svg><span>{{ total_items }}</span></a>{%endwith%}
    </div>
    <a class="btn btn-outline-primary" href="{% url 'accounts:profile' %}" role="button">Профиль</a>
  </div>


  {% block content %}

  {% endblock content %}
  </div>
</body>
</html>

test_app/templates/test_app/catalog.html
{% extends 'test_app/base.html' %}
{% load static %}
  {% block content %}
  <div class="container">
    <h1 class="maintitle" align="center">Товары:</h1>
    <div class="rov">
    {% for product in products %}
      <div class="col-lg-6 product_card">
        <div class="product_card_form" method="post">
          <figure>
            <a href="{{product.get_absolute_url}}"><img class="prev" src={{product.get_title_image.image.url}} /></a>
          </figure>
          <div class="description">
            <h3><a href="{{product.get_absolute_url}}">{{product.name}}</a></h3>
            <p>{{product.product_information}}</p>
            <p>{{product.description}}</p>
            <p><strong>Цена:</strong>&nbsp;{{product.price}}</p>
            <p><strong>Остаток:</strong>&nbsp;{{product.stock}}</p>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
    </div>
    {% endblock content %}

    

test_app/templates/test_app/index.html
{% extends 'test_app/base.html' %}
{% load static %}
{% block content %}
  <div class="container">

    <div class="rov">
      <div class="slider">
        <div class="viewport">
            <div class="slide_list">
                <div class="slide"><img src="https://ae01.alicdn.com/kf/Hc729a6126f72493597a9d52b5834f7f1w/750x300.png" alt=""></div>
                <div class="slide"><img src="https://ae01.alicdn.com/kf/Hbfc2867a0b224916817b787a90084f04e/750x300.png" alt=""></div>
                <div class="slide"><img src="https://ae01.alicdn.com/kf/H3485ba78fad340608964e2d573351f4f3.png" alt=""></div>
                <div class="slide"><img src="https://ae01.alicdn.com/kf/H8edf67abfe7d496791c157ad223ec240F/750x300.png" alt=""></div>
            </div>
            <button id="prevSlide">&#8249;</button>
            <button id="nextSlide">&#8250;</button>
            <div class="sliderNav btn-group" role="group">
                <ul>
                    <li><button class="btn btn-primary">1</button></li>
                    <li><button class="btn btn-primary">2</button></li>
                    <li><button class="btn btn-primary">3</button></li>
                </ul>
            </div>
        </div>
    </div>
    </div>

    <div class="rov">
      <aside class="">

      </aside>
      <main class="">
        
      </main>
    </div>

  </div>

  <script src="{% static 'test_app/slider.js' %}"></script>
{% endblock content %}

test_app/templates/test_app/productdetail.html
{% extends 'test_app/base.html' %}
{% load static %}
{% block content %}
<div class="container">
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'test_app:catalog' %}">Каталог</a></li>
    <li class="breadcrumb-item"><a href="{{product.category.get_absolute_url}}">{{product.category.name}}</a></li>
    <li class="breadcrumb-item active" aria-current="page"<a href="{{get_absolute_url}}">{{product.name}}</a></li>
  </ol>
</nav>
<div class="vrap">
  <aside class="product_image">
    <div class="pic">
      <img class="first" src="{% if product.get_title_image %}{{product.get_title_image.image.url}}{% else %}{% static "img/no_image.png" %}{% endif %}" alt='{{product_name}}' />
      {% for image in product.get_images %}
      <img class="second" src="{{image.image.url}}" alt="">
      {% endfor %}
    </div>
  </aside>
  <main class="product_description">
    <div class="description details">
    <h2>{{product.name}}</h2>
      <p>Наличие:
        {% if product.stock > 0 and product.available %}
          Есть в наличии
        {% else %}
          Нет в наличии
        {% endif %}
      </p>
      <p>{{product.description|linebreaks}}</p>
      <p><strong>Цена:</strong>&nbsp;{{product.price}}</p>
      <p><strong>Остаток:</strong>&nbsp;{{product.stock}}</p>
      <form id="productdata" class="form-label" action="{% url 'cart:cart_add' product.id %}" method="post">
        <div class="quantity">
          <button id="quantityAdd" class="btn btn-primary" type="button" name="button">+</button>
          {{cart_product_form.quantity}}
          <button id="quantitySubtract" class="btn btn-primary" type="button" name="button">-</button>
        </div>
        <div class="buttons">
          <button id="paynow" class="btn btn-primary" type="submit" name="button">Купить сейчас</button>
          <button id="addtocart" class="btn btn-primary" type="button" name="button">Добавить в корзину</button>
          <button id="wishlist" class="btn btn-primary" type="button" name="button">&#128525;</button>
        </div>
        {% csrf_token %}
      </form>
    </div>
  </main>
</div>
</div>


<script type="text/javascript">
  let quantityAdd = document.getElementById('quantityAdd');
  let quantitySubtract = document.getElementById('quantitySubtract');
  let quantityInp = document.getElementById('quantityInp');
  quantityInp.addEventListener('input', function(){
    if (quantityInp.value < 1) {
      quantityInp.value = 1;
    } else if (quantityInp.value > 100) {
      quantityInp.value = 100;
    }
    quantityInp.value = quantityInp.value.replace(/[^0-9]/g,'');
  })
  quantityAdd.addEventListener('click', function() {
    quantityInp.value++;
    if(quantityInp.value < 1) {
      quantityInp.value = 1;
    } else if (quantityInp.value > 100) {
      quantityInp.value = 100;
    }
    })
  quantitySubtract.addEventListener('click', function() {
    quantityInp.value--;
    if(quantityInp.value < 1) {
      quantityInp.value = 1;
    } else if (quantityInp.value > 100) {
      quantityInp.value = 100;
    }
  })

  let currentImg = document.querySelector('.product_detail__img img');
  let menemapImgs = document.querySelectorAll('.minimap_img');
  minimapImgs.forEach(function(img) {
    img.addEventListener('click', function(){
      currentImg.style.opacity = 0;
      setTimeout(() => {
        currentImg.src = img.src;
        currentImg.style.opacity = 1;
      }, 200)
    })
  })

</script>

<script type="text/javascript">
  function addToCart() {
    let productData = document.getElementById('productdata');
    let formData = new FormData(productData);
    console.log(formData.get('quantity'))
    let url = 'http://127.0.0.1:8000/cart/add/'+{{product.id}}+'/';
    let options = {method: 'POST',
                  headers: {enctype: "multipart/form-data", "Access-Control-Allow-Origin":"*"},
                  body: formData};
    fetch(url, options)
      .then(responce => {console.log(responce, formData)})
  }

let addtocartbtn = document.getElementById('addtocart');
addtocartbtn.addEventListener('click', addToCart);


</script>

{% endblock content %}