cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name="cart_remove"),
]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('test_app.urls', 'test_app'), namespace='test_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_app/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/', views.product_list, name='catalog'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
    views.product_detail,
    name='product_detail'),
    url(r'^(?P<category_slug>[-\w]+)/$',
    views.product_list,
    name='product_list_by_category'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label='Количество', widget=forms.TextInput(attrs={'id': 'quantityInp', 'class': 'quantity_input', 'value':1, 'pattern':'[0-9]' }))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from test_app.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from orders.forms import OrderCreateForm

def cart_detail(request):
    cart = Cart(request)
    form = OrderCreateForm()
    cart_product_form = CartAddProductForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'cart_product_form': cart_product_form, 'form': form})

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

cart/templates/cart/detail.html
{% extends "test_app/base.html" %}
{% load static %}
{% block content %}
    <div class="container">
      <h1>Корзина</h1>
      <div class="row_cart_empty">
      <div class="cart__detail">
        {% if cart|length == 0 %}
        <div class="cart__empty">
          <h2 class="cart__empty_headline">Корзина пуста :(</h2>
          <div class="cart__empty_img">
            <img class="img-fluid cart_i" src="{% static './images/shopping-cart.jpg' %}" alt="">
          </div>
          <a href="{% url 'test_app:catalog' %}" class="btn btn-primary">Продолжить покупки</a>
        </div>
        {% else %}
          <div class="cart__item_list">
            {% for item in cart %}
            {% with product=item.product %}
            <div class="cart__item">
              <div class="cart__item_img">
                <a href="{{product.get_absolute_url}}">
                  <img class="cart_img" src="
                    {% if product.get_title_image %}
                      {{product.get_title_image.image.url}}
                    {% else %}
                      {% static 'img/no_image.png' %}
                    {% endif %}
                  " alt="">
                </a>
              </div>
              <div class="cart__item_quantity">
                <form id="productdata" class="form-label" action="{% url 'cart:cart_add' product.id %}" method="post">
                  <div class="form_quantuty">
                    <div class="quantity">
                      <button id="quantityAdd" class="btn btn-primary quantity_plus" type="submit" name="button">+</button>
                      {{cart_product_form.quantity}}
                      <span style="display: none;">{{item.quantity}}</span>
                      <button id="quantitySubtract" class="btn btn-primary quantity_minus" type="submit" name="button">-</button>
                    </div>
                    <input type="hidden" name="update" value="True">
                    {% csrf_token %}
                  </div>
                </form>
              </div>
              <div class="product_description">
              <div class="cart__item_name">
                <p><strong>Название:</strong> {{product.name}}</p>
              </div>

              <div class="cart__item_cost">
                <p><strong>Стоимость:</strong> {{item.total_price}}</p>
                <p><strong>Цена за штуку:</strong> {{item.price}}</p>
              </div>
              <a href="{% url 'cart:cart_remove' product.id %}" class="btn btn-primary cart__item_remove">Удалить</a>
            </div>
            </div>
            {% endwith %}
            {% endfor %}

            <div class="row_cart">
                <div class="profile_data">
                  <div class="delivery">
                    <h2>Способ оплаты</h2>
                    <p>Для выбора способа оплаты, необходимо выбрать адрес доставки</p>
                  </div>
                  <div class="profile">
                    <form action="{% url 'orders:order_create' %}" method="post">
                      <p><i>Пожалуйста, заполните форму. Обязательные поля помечены </i><em>*</em></p>
                        <fieldset>
                          <legend>Контактная информация</legend>
                            <label for="name">Имя <em>*</em></label>
                              {{form.first_name}}<br>
                              <label for="telephone">Телефон</label>
                              {{form.phone}}<br>
                              <label for="address">Адрес <em>*</em></label>
                              {{form.address}}<br>
                              <label for="city">Город <em>*</em></label>
                              {{form.city}}<br>
                              <label for="delivery_way">Доставка <em>*</em></label>
                              {{form.delivery_way}}<br>
                              <label for="comment">Комментарий <em>*</em></label>
                              {{form.comment}}<br>
                            </fieldset>
                      <p><input class="btn btn-primary" type="submit" value="Отправить"></p>
                      {% csrf_token %}
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="cart__detail total">
            <div class="cart__total">
              <h5><strong>Сумма:</strong> {{cart.get_total_price}}</h5>
            </div>
            <a href="{% url 'test_app:catalog' %}" class="btn btn-primary">Продолжить покупки</a>
          </div>
          {% endif %}
          </div>
      </div>

      <script type="text/javascript">
        let forms = document.querySelectorAll('.form-label');

        forms.forEach((form, i) => {
          let quantityAdd = form.querySelector('.quantity_plus');
          let quantitySubtract = form.querySelector('.quantity_minus');
          let quantityInp = form.querySelector('.quantity_input');
          quantityInp.value = form.querySelector('span').innerText;

          quantityAdd.addEventListener('click', function() {
            quantityInp.value++;
            if(quantityInp.value < 1) {
              quantityInp.value = 1;
            } else if (quantityInp.value > 100) {
              quantityInp.value = 100;
            }
            })
          quantitySubtract.addEventListener('click', function() {
            quantityInp.value--;
            if(quantityInp.value < 1) {
              quantityInp.value = 1;
            } else if (quantityInp.value > 100) {
              quantityInp.value = 100;
            }
            })

          function quantityUpdate(e){
            e.preventDefault();
            let productData = form;
            let formData = new FormData(productData);
            let url = e.target.action;
            let options = {method: 'POST',
                          headers: {enctype: "multipart/form-data", "Access-Control-Allow-Origin":"*"},
                          body: formData};
            fetch(url, options)
              .then(responce => {console.log(responce, formData)})
          }
          form.addEventListener('submit', quantityUpdate)
        });



      </script>
{% endblock %}